// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MySecondExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "MySecondExtension.72659237-907c-4acb-a44b-9e17e56ce87a";
        public const string Name = "MySecondExtension";
        public const string Description = @"实体构建器生成，选中类名，根据类名生成对应构建器";
        public const string Language = "zh-CN";
        public const string Version = "1.2";
        public const string Author = "Lugas";
        public const string Tags = "";
    }
}
